### ISSUE TITLE
Wrong docker port configuration in Readme

### ISSUE THREAD

**Issue by ScholliYT** [maildev/maildev#307]
I just noticed that the docker command mentioned in the Readme is not working:
`$ docker run -p 1080:1080 -p 1025:1025 maildev/maildev`

This would need to have the port 1080/1025 internally. But the port 80/25 is used inside of the docker image. So the following command worked for me:
`$ docker run -p 1080:80 -p 1025:25 maildev/maildev`

Can sombody confirm this?

**Comment by xandermann** [comment]
I got the same problem here too, the ports ` 1080:80` and `1025:25` seem to work for me too.

**Comment by leosuncin** [comment]
This is because `latest` tag point to a old (but stable) image layer, the `1.1.0` tag have the same digest [9ae76db9e72a](https://hub.docker.com/layers/maildev/maildev/latest/images/sha256-9ae76db9e72ad3c41a34ffcc327bbd3525849a161d257888f41a8dc4262ec73f?context=explore) and was built exposing port 25 and 80

**Comment by RobertHeim** [comment]
It works fine when using the beta image:

```
docker run -p 1080:1080 -p 1025:1025 maildev/maildev:2.0.0-beta3
```

**Comment by soulteary** [comment]
hi,  @eduardomb08 @RobertHeim @leosuncin @xandermann @ScholliYT   We updated a new version docker image, hope it helps you
https://github.com/maildev/maildev/issues/382
