### ISSUE TITLE
All html attributes seem to be missing in HTML view

### ISSUE THREAD

**Issue by garth** [maildev/maildev#403]
Using v2.0.2 docker image. In html view all html element attributes are stripped. When viewing the email src the attributes are present but encoded with "quoted-printable", maybe that is why they get stripped? v1.1.1 works fine.

**Comment by beholderrk** [comment]
![image](https://user-images.githubusercontent.com/841755/161730414-df4c3709-5e0a-4b92-a874-732c232e65e1.png)
Yep, html email broken in 2.0.2 version

**Comment by kossa** [comment]
Getting the same issue(without docker)

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1175584/162612399-e55479c5-286c-4d19-8ebc-3c958b37c9ad.png">

![image](https://user-images.githubusercontent.com/1175584/162612422-424c5519-0355-4887-96b8-1bbb00474328.png)

Mail preview:

![image](https://user-images.githubusercontent.com/1175584/162612432-e741aef7-e1f8-43c8-88fa-3b3fb941e505.png)

**Comment by dcrouch79** [comment]
The `=3D` characters are how the [Quoted Printable](https://en.wikipedia.org/wiki/Quoted-printable) encoding system encodes the equals sign. See [here](https://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html) for more details.

The missing html elements/attributes is due to how the html is being sanitised. I've proposed a fix for this. See #398 and #408.

**Comment by djfarrelly** [comment]
Fixed in https://github.com/maildev/maildev/releases/tag/v2.0.4

**Comment by beholderrk** [comment]
@djfarrelly Thx!
